
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Landingspot2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1803, 3, 2, 0}, {1803, 3, 1, 0}, {1803, 3, 0, 0}// 1	2	3	
			, {1803, 3, -1, 0}, {1803, 3, -2, 0}, {1802, 2, 3, 0}// 4	5	6	
			, {1802, 1, 3, 0}, {1802, 0, 3, 0}, {1802, -1, 3, 0}// 7	8	9	
			, {1802, -2, 3, 0}, {1811, 3, 3, 0}, {1812, -3, 3, 0}// 10	11	12	
			, {1805, -3, 2, 0}, {1805, -3, 1, 0}, {1805, -3, 0, 0}// 13	14	15	
			, {1805, -3, -1, 0}, {1805, -3, -2, 0}, {16827, 1, 2, 5}// 16	17	18	
			, {16827, 0, 2, 5}, {16827, -1, 2, 5}, {16828, 2, 2, 5}// 19	20	21	
			, {16826, -2, 2, 5}, {16825, 2, 1, 5}, {16825, 2, 0, 5}// 22	23	24	
			, {16825, 2, -1, 5}, {16824, -2, 1, 5}, {16824, -2, 0, 5}// 25	26	27	
			, {16824, -2, -1, 5}, {16823, 2, -2, 5}, {16822, 1, -2, 5}// 28	29	30	
			, {16822, 0, -2, 5}, {16822, -1, -2, 5}, {16821, -2, -2, 5}// 31	32	33	
			, {16782, 1, 1, 5}, {16780, -1, 1, 5}, {16781, 0, 1, 5}// 34	35	36	
			, {16776, 1, -1, 5}, {16774, -1, -1, 5}, {16775, 0, -1, 5}// 37	38	39	
			, {16777, -1, 0, 5}, {16779, 1, 0, 5}, {16778, 0, 0, 5}// 40	41	42	
			, {1813, 3, -3, 0}, {1810, -3, -3, 0}, {1804, -2, -3, 0}// 43	44	45	
			, {1804, -1, -3, 0}, {1804, 0, -3, 0}, {1804, 1, -3, 0}// 46	47	48	
			, {1804, 2, -3, 0}// 49	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Landingspot2AddonDeed();
			}
		}

		[ Constructable ]
		public Landingspot2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public Landingspot2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Landingspot2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Landingspot2Addon();
			}
		}

		[Constructable]
		public Landingspot2AddonDeed()
		{
			Name = "Landingspot2";
		}

		public Landingspot2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}