
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Landingspot1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1836, -2, 3, 0}, {1835, 3, 3, 0}, {1829, -2, 2, 0}// 1	2	3	
			, {1829, -2, 1, 0}, {1829, -2, 0, 0}, {1826, 2, 3, 0}// 4	5	6	
			, {1826, 1, 3, 0}, {1826, 0, 3, 0}, {1826, -1, 3, 0}// 7	8	9	
			, {1827, 3, 2, 0}, {1827, 3, 1, 0}, {1827, 3, 0, 0}// 10	11	12	
			, {17197, 1, 2, 5}, {17197, 0, 2, 5}, {17197, 2, 2, 5}// 13	14	15	
			, {17197, 2, 1, 5}, {17197, 2, 0, 5}, {17196, -1, 2, 5}// 16	17	18	
			, {17196, -1, 1, 5}, {17196, -1, 0, 5}, {17195, 1, 1, 5}// 19	20	21	
			, {17194, 0, 1, 5}, {17193, 1, 0, 5}, {17192, 0, 0, 5}// 22	23	24	
			, {1834, -2, -2, 0}, {1837, 3, -2, 0}, {1829, -2, -1, 0}// 25	26	27	
			, {1828, 2, -2, 0}, {1828, 1, -2, 0}, {1828, 0, -2, 0}// 28	29	30	
			, {1828, -1, -2, 0}, {1827, 3, -1, 0}, {17196, -1, -1, 5}// 31	32	33	
			, {17197, 2, -1, 5}, {17196, 0, -1, 5}, {17196, 1, -1, 5}// 34	35	36	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Landingspot1AddonDeed();
			}
		}

		[ Constructable ]
		public Landingspot1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public Landingspot1Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Landingspot1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Landingspot1Addon();
			}
		}

		[Constructable]
		public Landingspot1AddonDeed()
		{
			Name = "Landingspot1";
		}

		public Landingspot1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}