
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LandingspotAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11723, 1, 1, 0}, {11576, 1, 2, 0}, {11190, 2, -1, 0}// 1	2	3	
			, {11576, 1, -1, 0}, {11191, 2, 2, 0}, {11578, 2, 0, 0}// 4	5	6	
			, {11578, 2, 1, 0}, {11726, 1, 0, 0}, {1183, 1, -2, 0}// 7	8	9	
			, {1183, 2, -2, 0}, {11191, -1, -1, 0}, {11190, -1, 2, 0}// 10	11	12	
			, {11576, 0, -1, 0}, {11578, -1, 0, 0}, {11578, -1, 1, 0}// 13	14	15	
			, {11576, 0, 2, 0}, {11725, 0, 0, 0}, {11724, 0, 1, 0}// 16	17	18	
			, {1183, -2, -2, 0}, {1183, -1, -2, 0}, {1183, 0, -2, 0}// 19	20	21	
			, {1183, -2, -1, 0}, {1183, -2, 0, 0}, {1183, -2, 1, 0}// 22	23	24	
			, {1183, -2, 2, 0}// 25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LandingspotAddonDeed();
			}
		}

		[ Constructable ]
		public LandingspotAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LandingspotAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LandingspotAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LandingspotAddon();
			}
		}

		[Constructable]
		public LandingspotAddonDeed()
		{
			Name = "Landingspot";
		}

		public LandingspotAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}